import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createHandler} from '../server/handler.ts';
import {accountToken,readAccountToken,ACCOUNT_COOKIE,hashPassword,verifyPassword} from '../server/accounts.ts';
import {emptyChart} from '../lib/drill-chart.ts';
const env={ADMIN_PASSWORD:'existing-admin-password',SESSION_SECRET:'test-session-secret-at-least-32-characters'};
const pass='0123';
const chart={...emptyChart(),id:randomUUID(),name:'공개 테스트',shared:true};
const req=(path,body,cookie,method)=>new Request('https://club.example/api/'+path,{method:method||(body===undefined?'GET':'POST'),headers:{origin:'https://club.example','content-type':'application/json',...(cookie?{cookie}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
const cookie=r=>r.headers.get('set-cookie')?.split(';')[0];
function harness(){
 const users=new Map(),counts=new Map(),charts=[chart,{...chart,id:randomUUID(),shared:false}],state={bootstrapped:false,writes:0};
 const accounts={byId:async id=>users.get(id)||null,byName:async key=>[...users.values()].find(x=>x.name_key===key)||null,list:async()=>[...users.values()],setupAvailable:async()=>!state.bootstrapped,
 create:async(u,bootstrap=false)=>{if([...users.values()].some(x=>x.name_key===u.name_key)||(bootstrap&&state.bootstrapped))return null;const saved={...u,role:bootstrap?'admin':'member',active:true,session_version:1,created_at:new Date().toISOString()};users.set(u.id,saved);if(bootstrap)state.bootstrapped=true;return saved;},
 changePassword:async(id,v,hash)=>{const u=users.get(id);if(!u?.active||u.session_version!==v)return null;const saved={...u,password_hash:hash,session_version:v+1};users.set(id,saved);return saved;},
 manage:async(actor,id,role,active)=>{const a=users.get(actor.id),u=users.get(id);if(!a?.active||a.role!=='admin'||a.session_version!==actor.session_version||!u||id===a.id)return null;const saved={...u,role,active,session_version:u.session_version+1};users.set(id,saved);return saved;}};
 const store={list:async all=>charts.filter(c=>all||c.shared),save:async c=>{state.writes++;return c;},attempt:async key=>{counts.set(key,(counts.get(key)||0)+1);return counts.get(key)<=10;}};
 const handler=createHandler({env:()=>env,accounts:()=>accounts,store:()=>store});
 const call=(path,body,c)=>handler(req(path,body,c),{ip:'192.0.2.1'});
 return {call,handler,users,counts,accounts,store,state};
}
async function setup(h){const r=await h.call('setup',{name:'관리자',password:pass,setupPassword:env.ADMIN_PASSWORD});assert.equal(r.status,200);return {cookie:cookie(r),user:(await r.json()).user};}
async function register(h,name='일반회원'){const r=await h.call('register',{name,password:pass});assert.equal(r.status,200);return {cookie:cookie(r),user:(await r.json()).user};}
test('passwords are salted scrypt hashes; account tokens reject tampering, expiry and secret rotation',async()=>{const a=await hashPassword(pass),b=await hashPassword(pass);assert.notEqual(a,b);assert.equal(await verifyPassword(pass,a),true);assert.equal(await verifyPassword('wrong',a),false);const u={id:randomUUID(),session_version:1};const token=accountToken(u,env,1000);assert.deepEqual(readAccountToken(ACCOUNT_COOKIE+'='+token,env,1000),{id:u.id,v:1});assert.equal(readAccountToken(ACCOUNT_COOKIE+'='+token+'x',env,1000),null);assert.equal(readAccountToken(ACCOUNT_COOKIE+'='+token,env,43201001),null);assert.equal(readAccountToken(ACCOUNT_COOKIE+'='+token,{...env,SESSION_SECRET:'changed-secret-at-least-32-characters'},1000),null);});
test('public reads only shared charts and cannot write or list members',async()=>{const h=harness();assert.equal((await (await h.call('charts')).json()).length,1);assert.equal((await h.call('charts',chart)).status,403);assert.equal((await h.call('users')).status,403);assert.equal(h.state.writes,0);});
test('signup defaults to member; hashes never leave API; normalized duplicate names blocked',async()=>{const h=harness();const r=await h.call('register',{name:' Test User ',password:pass});assert.equal(r.status,200);const body=await r.json();assert.equal(body.user.role,'member');assert.equal(body.user.password_hash,undefined);assert.equal(body.user.session_version,undefined);assert.match(r.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);assert.equal((await h.call('register',{name:'test  user',password:pass})).status,409);assert.equal((await h.call('register',{name:'공격자',password:pass,role:'admin'})).status,400);});
test('first admin requires old secret, cannot run twice, old admin cookies cannot bypass it',async()=>{const h=harness();assert.equal((await h.call('setup',{name:'관리자',password:pass,setupPassword:'incorrect'})).status,401);await setup(h);assert.equal((await h.call('setup',{name:'다른관리자',password:pass,setupPassword:env.ADMIN_PASSWORD})).status,409);assert.equal((await (await h.call('session')).json()).setupAvailable,false);assert.equal((await h.call('users',undefined,'bowling_fit_session=old-admin-token')).status,403);});
test('member cannot change permissions or write; editor can write but cannot manage users',async()=>{const h=harness(),a=await setup(h),m=await register(h);assert.equal((await h.call('charts',chart,m.cookie)).status,403);assert.equal((await h.call('users',{id:m.user.id,role:'admin',active:true},m.cookie)).status,403);assert.equal((await h.call('users',{id:m.user.id,role:'editor',active:true},a.cookie)).status,200);assert.equal((await h.call('charts',chart,m.cookie)).status,403);const login=await h.call('login',{name:'일반회원',password:pass});const c=cookie(login);assert.equal((await h.call('charts',chart,c)).status,200);assert.equal((await (await h.call('charts',undefined,c)).json()).length,2);assert.equal((await h.call('users',undefined,c)).status,403);});
test('suspension, demotion, and stale sessions are enforced on every request',async()=>{const h=harness(),a=await setup(h),m=await register(h);await h.call('users',{id:m.user.id,role:'editor',active:true},a.cookie);const login=await h.call('login',{name:'일반회원',password:pass});const c=cookie(login);await h.call('users',{id:m.user.id,role:'member',active:false},a.cookie);assert.equal((await h.call('charts',chart,c)).status,403);assert.equal((await h.call('login',{name:'일반회원',password:pass})).status,401);assert.equal((await (await h.call('session',undefined,c)).json()).user,null);});
test('admin cannot demote or suspend self; member list never contains password hashes',async()=>{const h=harness(),a=await setup(h);assert.equal((await h.call('users',{id:a.user.id,role:'member',active:false},a.cookie)).status,409);const data=await (await h.call('users',undefined,a.cookie)).json();assert.equal(data[0].password_hash,undefined);assert.equal(data[0].name_key,undefined);});
test('password change requires current password, invalidates previous sessions, and new password logs in',async()=>{const h=harness(),m=await register(h);assert.equal((await h.call('password',{currentPassword:'incorrect',newPassword:'9876'},m.cookie)).status,401);const r=await h.call('password',{currentPassword:pass,newPassword:'9876'},m.cookie);assert.equal(r.status,200);assert.equal((await (await h.call('session',undefined,m.cookie)).json()).user,null);assert.equal((await h.call('login',{name:'일반회원',password:pass})).status,401);assert.equal((await h.call('login',{name:'일반회원',password:'9876'})).status,200);assert.equal((await (await h.call('session',undefined,cookie(r))).json()).user.id,m.user.id);});
test('CSRF, oversized signup, role injection and throttling fail before writes',async()=>{const h=harness();const cross=req('register',{name:'회원',password:pass});cross.headers.set('origin','https://other.example');assert.equal((await h.handler(cross)).status,403);assert.equal((await h.call('register',{name:'x'.repeat(5000),password:pass})).status,413);for(let i=0;i<10;i++)assert.equal((await h.call('login',{name:'없는회원',password:pass})).status,401);assert.equal((await h.call('login',{name:'없는회원',password:pass})).status,429);assert.equal(h.users.size,0);});
test('public reading works without auth secret, registration fails closed',async()=>{const h=harness();const handler=createHandler({env:()=>({}),accounts:()=>h.accounts,store:()=>h.store});assert.equal((await handler(req('charts'))).status,200);assert.equal((await handler(req('register',{name:'회원',password:pass}))).status,503);});

test('new passwords require exactly four ASCII digits; existing long passwords can migrate',async()=>{const h=harness();for(const password of ['123','12345','12a4','１２３４'])assert.equal((await h.call('register',{name:'검증회원',password})).status,400);const m=await register(h);const u=h.users.get(m.user.id);h.users.set(u.id,{...u,password_hash:await hashPassword('legacy-password-long')});const r=await h.call('login',{name:u.name,password:'legacy-password-long'});assert.equal(r.status,200);const c=cookie(r);assert.equal((await h.call('password',{currentPassword:'legacy-password-long',newPassword:'12345'},c)).status,400);assert.equal((await h.call('password',{currentPassword:'legacy-password-long',newPassword:'0007'},c)).status,200);assert.equal((await h.call('login',{name:u.name,password:'0007'})).status,200);});

test('large ink charts save losslessly for admins; public writes and invalid points are rejected',async()=>{const h=harness(),a=await setup(h);const ink=[{id:'ink1',page:'sheet',color:'#203d38',width:3,points:Array.from({length:4000},(_,i)=>[i%800,i%1000])}];const payload={...chart,ink};assert.ok(JSON.stringify(payload).length>30000);const r=await h.call('charts',payload,a.cookie);assert.equal(r.status,200);assert.deepEqual((await r.json()).ink,ink);assert.equal((await h.call('charts',payload)).status,403);assert.equal((await h.call('charts',{...chart,ink:[{...ink[0],points:[[900,0]]}]},a.cookie)).status,400);assert.equal(h.state.writes,1);});

test('authorized chart save preserves Korean measurements, grip choice and GNS',async()=>{const h=harness(),a=await setup(h);const payload={...chart,grip:'twohand',bridge:'기존과 동일',middle:{...chart.middle,diameter:'조금 넓게',forward:'중립',insertStyle:'GNS'}};const r=await h.call('charts',payload,a.cookie);assert.equal(r.status,200);const saved=await r.json();assert.equal(saved.grip,'twohand');assert.equal(saved.bridge,'기존과 동일');assert.equal(saved.middle.diameter,'조금 넓게');assert.equal(saved.middle.insertStyle,'GNS');assert.equal((await h.call('charts',payload)).status,403);});
