import test from 'node:test';
import assert from 'node:assert/strict';
import {makeSession,readSession,sessionCookie,COOKIE} from '../server/auth.ts';
import {createHandler} from '../server/handler.ts';
import {emptyChart} from '../lib/drill-chart.ts';
const env={ADMIN_PASSWORD:'test-admin-password-long',CLUB_PASSWORD:'test-club-password',SESSION_SECRET:'test-session-secret-at-least-32-characters'};
const cookie=(role)=>`${COOKIE}=${makeSession(role,env)}`;
const chart={...emptyChart(),id:'03cf5678-3ab5-4321-a987-55f0788dab65',name:'테스트',shared:true};
const rows=[chart,{...chart,id:'03cf5678-3ab5-4321-a987-55f0788dab66',shared:false}];
let writes=0,attempts=0;
const handler=createHandler({env:()=>env,store:()=>({list:async admin=>rows.filter(c=>admin||c.shared),save:async c=>{writes++;return c;},attempt:async()=>++attempts<=10})});
const request=(path,role,method='GET',body)=>new Request('https://club.example/api/'+path,{method,headers:{...(role?{cookie:cookie(role)}:{}),...(method==='POST'?{origin:'https://club.example','content-type':'application/json'}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
test('session tampering, expiry, rotation and cookie flags',()=>{const now=Date.now();const token=makeSession('admin',env,now);assert.equal(readSession(`${COOKIE}=${token}`,env,now),'admin');assert.equal(readSession(`${COOKIE}=${token}x`,env,now),null);assert.equal(readSession(`${COOKIE}=${token}`,env,now+43200001),null);assert.equal(readSession(`${COOKIE}=${token}`,{...env,ADMIN_PASSWORD:'rotated-admin-password'},now),null);assert.match(sessionCookie(token,true),/HttpOnly; SameSite=Strict/);assert.match(sessionCookie(token,true),/; Secure$/);});
test('anonymous cannot read or write charts',async()=>{assert.equal((await handler(request('charts'))).status,401);assert.equal((await handler(request('charts',null,'POST',chart))).status,401);});
test('club reads only shared charts and cannot write even with handcrafted requests',async()=>{const r=await handler(request('charts','club'));const data=await r.json();assert.equal(data.length,1);assert.equal(data[0].shared,true);const n=writes;assert.equal((await handler(request('charts','club','POST',chart))).status,403);assert.equal(writes,n);assert.equal(r.headers.get('cache-control'),'no-store, private');});
test('admin sees all charts and can save shared state',async()=>{assert.equal((await (await handler(request('charts','admin'))).json()).length,2);assert.equal((await handler(request('charts','admin','POST',chart))).status,200);assert.equal((await handler(request('charts','admin','POST',{...chart,spec:{...chart.spec,ovalShape:'oval',ovalLong:.5,ovalShort:1}}))).status,400);});
test('cross-origin state changes are rejected',async()=>{const req=request('charts','admin','POST',chart);req.headers.set('origin','https://other.example');assert.equal((await handler(req)).status,403);});
test('login accepts correct role password and throttles attempts',async()=>{attempts=0;const login=await handler(request('login',null,'POST',{role:'club',password:env.CLUB_PASSWORD}),{ip:'192.0.2.1'});assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/HttpOnly/);assert.equal((await handler(request('login',null,'POST',{role:'admin',password:env.CLUB_PASSWORD}),{ip:'192.0.2.1'})).status,401);for(let i=0;i<8;i++)await handler(request('login',null,'POST',{role:'club',password:'wrong'}),{ip:'192.0.2.1'});assert.equal((await handler(request('login',null,'POST',{role:'club',password:'wrong'}),{ip:'192.0.2.1'})).status,429);});
test('missing settings fail closed',async()=>{const h=createHandler({env:()=>({}),store:()=>{throw Error('must not connect')}});assert.equal((await h(request('session'))).status,503);});
