import {useEffect,useState} from 'react';
import {api,roleName,type User} from './account-api';
function MemberRow({member,self,onSaved}:{member:User;self:boolean;onSaved:(u:User)=>void}){
 const [role,setRole]=useState(member.role),[active,setActive]=useState(member.active),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setRole(member.role);setActive(member.active);},[member]);
 async function save(){setBusy(true);setError('');try{onSaved(await api('users',{id:member.id,role,active}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <tr><td><strong>{member.name}{self?' (나)':''}</strong><small>{new Date(member.created_at).toLocaleDateString('ko-KR')}</small></td><td><select aria-label={`${member.name} 권한`} value={role} disabled={self||busy} onChange={e=>setRole(e.target.value as User['role'])}>{Object.entries(roleName).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></td><td><label className="active-check"><input type="checkbox" checked={active} disabled={self||busy} onChange={e=>setActive(e.target.checked)}/>{active?'활성':'정지'}</label></td><td><button disabled={self||busy||(role===member.role&&active===member.active)} onClick={save}>{busy?'저장 중…':'적용'}</button>{error&&<p className="login-error" role="alert">{error}</p>}</td></tr>;
}
export default function AccountPage({user,onUser,onBack,onLogout}:{user:User;onUser:(u:User)=>void;onBack:()=>void;onLogout:()=>void}){
 const [members,setMembers]=useState<User[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState('');
 const [current,setCurrent]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[passwordError,setPasswordError]=useState('');
 async function load(){setLoading(true);setError('');try{setMembers(await api('users'));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{if(user.role==='admin')load();},[user.role]);
 async function change(e:React.FormEvent){e.preventDefault();setMessage('');setPasswordError('');if(password!==confirm){setPasswordError('새 비밀번호 확인이 일치하지 않습니다.');return;}setBusy(true);try{const d=await api('password',{currentPassword:current,newPassword:password});onUser(d.user);setCurrent('');setPassword('');setConfirm('');setMessage('비밀번호를 변경했어요. 다른 기기의 로그인은 해제됩니다.');}catch(e){setPasswordError((e as Error).message);}finally{setBusy(false);}}
 return <main className="account-page"><header className="account-heading"><div><p className="eyebrow">FIT STUDIO · ACCOUNT</p><h1>{user.name}</h1><p>{roleName[user.role]} · {user.role==='member'?'공개 차트를 조회할 수 있어요. 편집 권한은 관리자에게 요청하세요.':'차트를 등록하고 수정할 수 있어요.'}</p></div><div className="account-actions"><button onClick={onBack}>차트로 돌아가기</button><button onClick={onLogout}>로그아웃</button></div></header>{user.role==='admin'&&<section className="panel account-panel"><h2>회원 관리</h2><p>일반 회원은 조회, 편집자는 차트 등록·수정, 관리자는 회원 관리까지 가능합니다. 정지된 계정은 로그인할 수 없습니다. 공개 조회는 누구나 가능합니다.</p><p>권한이나 상태를 변경하면 해당 회원은 다시 로그인해야 합니다. 내 계정의 권한·상태는 변경할 수 없습니다.</p><div className="account-actions"><input aria-label="회원 이름 검색" placeholder="회원 이름 검색" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={load} disabled={loading}>새로고침</button></div>{error?<p className="login-error" role="alert">{error}</p>:loading?<p>회원 목록을 불러오는 중…</p>:<div className="members-table-wrap"><table className="members-table"><thead><tr><th>이름 / 가입일</th><th>권한</th><th>상태</th><th>변경</th></tr></thead><tbody>{members.filter(m=>m.name.toLowerCase().includes(query.toLowerCase())).map(m=><MemberRow key={m.id} member={m} self={m.id===user.id} onSaved={updated=>setMembers(p=>p.map(x=>x.id===updated.id?updated:x))}/>)}</tbody></table></div>}</section>}<section className="panel account-panel"><h2>비밀번호 변경</h2><form onSubmit={change} className="password-form"><fieldset className="account-fields" disabled={busy}><label>현재 비밀번호<input type="password" autoComplete="current-password" required minLength={1} maxLength={128} value={current} onChange={e=>setCurrent(e.target.value)}/></label><label>새 비밀번호<input type="password" autoComplete="new-password" required minLength={4} maxLength={4} inputMode="numeric" pattern="[0-9]{4}" placeholder="숫자 4자리" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>새 비밀번호 확인<input type="password" autoComplete="new-password" required minLength={4} maxLength={4} inputMode="numeric" pattern="[0-9]{4}" placeholder="숫자 4자리" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="save-button" type="submit" disabled={busy}>{busy?'변경 중…':'비밀번호 변경'}</button>{passwordError&&<p className="login-error" role="alert">{passwordError}</p>}{message&&<p role="status">{message}</p>}</fieldset></form></section></main>;
}
