import {useEffect,useRef,useState} from 'react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Measure,parseInches,formatInches as f} from '@/lib/drill-chart';
export function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:string[][];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
export function Inch({label,value,onChange,min=-2,max=7,unit='in',fractions=true}:{label:string;value:Measure;onChange:(v:Measure)=>void;min?:number;max?:number;unit?:string;fractions?:boolean}){
 const [raw,setRaw]=useState(value===null?'':String(value));const [err,setErr]=useState('');const input=useRef<HTMLInputElement>(null);const emitted=useRef<Measure|undefined>(undefined);
 useEffect(()=>{if(emitted.current===value){emitted.current=undefined;return;}emitted.current=undefined;setRaw(value===null?'':String(value));setErr('');input.current?.setCustomValidity('');},[value]);
 function update(text:string){setRaw(text);try{const n=parseInches(text);if(n!==null&&(n<min||n>max))throw Error(`${min}〜${max} ${unit} 범위로 입력하세요.`);setErr('');input.current?.setCustomValidity('');emitted.current=n;onChange(n);}catch(e){const msg=(e as Error).message;setErr(msg);input.current?.setCustomValidity(msg);}}
 return <label className="precise-input"><span>{label}</span><div><input ref={input} aria-label={label} aria-invalid={!!err} value={raw} placeholder={fractions?'예: 7/8':'미입력'} onChange={e=>update(e.target.value)}/><small>{unit}</small></div><span className={err?'input-error':'input-equivalent'}>{err|| (value===null?'미입력':fractions?`${f(value)}″ · ${value} in`:String(value)+' '+unit)}</span></label>
}
export function Text({label,value,onChange,max=120,placeholder=''}:{label:string;value:string;onChange:(s:string)=>void;max?:number;placeholder?:string}){return <label>{label}<input value={value} maxLength={max} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}

export function Pitch({axis,value,onChange}:{axis:'forward'|'lateral';value:Measure;onChange:(n:Measure)=>void}){const [direction,setDirection]=useState(value!==null&&value<0?-1:1);useEffect(()=>{if(value!==null&&value!==0)setDirection(value<0?-1:1);},[value]);const sign=direction;return <div className="pitch-input"><Inch label={axis==='forward'?'전후 피치':'좌우 피치'} value={value===null?null:Math.abs(value)} onChange={n=>onChange(n===null?null:n*sign)} min={0} max={2}/><Choice label={axis==='forward'?'전후 방향':'좌우 방향'} value={String(sign)} onChange={s=>{setDirection(Number(s));if(value!==null)onChange(Math.abs(value)*Number(s));}} items={axis==='forward'?[['1','F · 포워드'],['-1','R · 리버스']]:[['1','오른쪽'],['-1','왼쪽']]}/></div>}
