import {useEffect,useState} from 'react';
import {CircleDot,Search,Printer} from 'lucide-react';
import {Chart,normalizeChart} from '@/lib/drill-chart';
import {InkSurface,InkPrint} from './ink-board';
import {WorkSheet} from './work-sheet';
export default function ClubView({onAdminLogin,accountLabel}:{onAdminLogin:()=>void;accountLabel:string}){const [mode,setMode]=useState<'numbers'|'sheet'|'ball'>('numbers');const [charts,setCharts]=useState<Chart[]>([]);const [selected,setSelected]=useState('');const [query,setQuery]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/charts');const data=await r.json();if(!r.ok)throw Error(data.error);const rows=data.map(normalizeChart) as Chart[];setCharts(rows);setSelected(id=>rows.some(c=>c.id===id)?id:rows[0]?.id||'');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);const chart=charts.find(c=>c.id===selected);const results=charts.filter(c=>(c.name+' '+c.ball).toLowerCase().includes(query.toLowerCase()));
 return <><div className="app-shell"><header className="topbar"><span className="brand"><span className="brand-icon"><CircleDot size={24}/></span>FIT<span className="brand-light">STUDIO</span></span><span className="header-note">공개 차트 · 읽기 전용</span><button className="logout-button" onClick={onAdminLogin}>{accountLabel}</button></header><div className="club-layout"><aside className="club-list"><h2>클럽 지공차트 <small>{charts.length}</small></h2><div className="search"><Search size={16}/><input aria-label="볼러 또는 볼 이름 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="볼러 또는 볼 이름"/></div><button className="refresh-button" onClick={load} disabled={loading}>목록 새로고침</button>{loading?<p className="empty">불러오는 중…</p>:error?<p className="login-error" role="alert">{error}</p>:results.length?results.map(c=><button className={'chart-item '+(selected===c.id?'selected':'')} key={c.id} onClick={()=>setSelected(c.id)}><span><strong>{c.name}</strong><small>{c.ball||'기본 차트'} · {c.updated?.slice(0,10)}</small></span></button>):<p className="empty">{query?'검색 결과가 없어요.':'아직 공유된 차트가 없어요.'}</p>}</aside><main className="club-content">{chart&&!loading&&!error?<><div className="club-heading"><div><div className="eyebrow">SHARED FITTING RECORD</div><h1>{chart.name} · {chart.ball||'지공차트'}</h1></div><button className="print-button" onClick={()=>window.print()}><Printer size={17}/>인쇄 / PDF</button></div><div className="mode-switch viewer-modes"><button aria-pressed={mode==='numbers'} onClick={()=>setMode('numbers')}>수치 작업표</button><button aria-pressed={mode==='sheet'} onClick={()=>setMode('sheet')}>필기 작업표</button><button aria-pressed={mode==='ball'} onClick={()=>setMode('ball')}>볼 필기</button></div>{mode==='numbers'?<WorkSheet c={chart} dirty={false}/>:<><InkSurface page={mode} strokes={chart.ink||[]}/>{!chart.ink?.some(s=>s.page===mode)&&<p className="ink-help">이 페이지에는 저장된 필기가 없어요.</p>}</>}</>:<div className="club-placeholder"><CircleDot size={50}/><p>{error?'목록을 다시 불러와주세요.':loading?'차트를 불러오고 있어요.':'목록에서 공유 차트를 선택하세요.'}</p></div>}</main></div></div>{chart&&!error&&!loading&&<div className="print-only"><WorkSheet compact={false} c={chart} dirty={false}/><InkPrint c={chart}/></div>}</>;
}
