import {useRef,useState} from 'react';
import {Pencil,Eraser,Undo2,Redo2,Trash2,Hand} from 'lucide-react';
import {INK_COLORS,MAX_INK_POINTS,hitsStroke,strokePath,type InkPage,type InkStroke} from '@/lib/ink';
import type {Chart} from '@/lib/drill-chart';
function Template({page}:{page:InkPage}){return <g pointerEvents="none"><rect width="800" height="1000" rx="18" fill="#fff"/><text x="40" y="50" fill="#284e45" fontSize="23" fontWeight="700">{page==='sheet'?'지공 필기 작업표':'볼 배치 · 자유 메모'}</text><text x="40" y="78" fill="#82938b" fontSize="13">{page==='sheet'?'스팬 · 피치 · 홀 규격을 자유롭게 기록하세요':'빈 볼 참고도 · 홀 위치와 방향을 직접 표시하세요 · 축척 없음'}</text>{page==='ball'?<><circle cx="400" cy="350" r="220" fill="#f4f8f5" stroke="#b8cfc3" strokeWidth="2"/><ellipse cx="400" cy="350" rx="220" ry="64" fill="none" stroke="#c8d7cf" strokeDasharray="7 7"/><path d="M400 130V570M180 350H620" stroke="#c8d7cf" strokeDasharray="7 7"/><text x="40" y="645" fontSize="16" fill="#668375">레이아웃 / 방향 / 메모</text>{[690,750,810,870,930].map(y=><line key={y} x1="40" x2="760" y1={y} y2={y} stroke="#e3ebe6"/>)}</>:<>{['스팬 / 브리지 / 측정 기준','중지 · 외경 / 깊이 / 전후 피치 / 좌우 피치','약지 · 외경 / 깊이 / 전후 피치 / 좌우 피치','엄지 · 외경 / 깊이 / 피치 / 타원','PAP / 레이아웃 / 작업 메모'].map((t,i)=><g key={t}><rect x="32" y={110+i*170} width="736" height="155" rx="10" fill={i%2?'#fff':'#f8faf8'} stroke="#dae6de"/><text x="50" y={138+i*170} fill="#638273" fontSize="14">{t}</text><line x1="50" x2="750" y1={210+i*170} y2={210+i*170} stroke="#e6eee8"/></g>)}</>}<text x="40" y="987" fontSize="11" fill="#7e9186">FREEHAND NOTES · 필기는 수치 입력값으로 자동 변환되지 않습니다.</text></g>}
export function InkSurface({strokes,page,...props}:{strokes:InkStroke[];page:InkPage}&React.SVGProps<SVGSVGElement>){return <svg {...props} viewBox="0 0 800 1000" className={'ink-surface '+(props.className||'')} aria-label={page==='sheet'?'손글씨 지공 작업표':'손글씨 볼 배치도'}><Template page={page}/><g pointerEvents="none">{strokes.filter(s=>s.page===page).map(s=><path key={s.id} d={strokePath(s.points)} stroke={s.color} strokeWidth={s.width} fill="none" strokeLinecap="round" strokeLinejoin="round"/>)}</g></svg>}
export function InkPrint({c}:{c:Chart}){return <>{(['sheet','ball'] as const).filter(page=>c.ink?.some(s=>s.page===page)).map(page=><section className="ink-print-page" key={page}><header><strong>{c.name} · {c.ball||'지공차트'}</strong><span>{c.spec.date} · 자유 필기</span></header><InkSurface strokes={c.ink||[]} page={page}/></section>)}</>}
export function InkBoard({strokes,onChange,disabled=false}:{strokes:InkStroke[];onChange:(s:InkStroke[])=>void;disabled?:boolean}){
 const [page,setPage]=useState<InkPage>('sheet'),[tool,setTool]=useState<'pen'|'eraser'>('pen'),[color,setColor]=useState<typeof INK_COLORS[number]>(INK_COLORS[0]),[width,setWidth]=useState(3),[finger,setFinger]=useState(false),[draft,setDraft]=useState<InkStroke|null>(null),[message,setMessage]=useState(''),[history,setHistory]=useState<InkStroke[][]>([]),[redo,setRedo]=useState<InkStroke[][]>([]);
 const active=useRef<{id:number;stroke:InkStroke|null;before:InkStroke[];erased:InkStroke[];scrollY:number;pan:boolean}|null>(null);
 function commit(next:InkStroke[],before=strokes){setHistory(h=>[...h.slice(-19),before]);setRedo([]);onChange(next);}
 function point(e:React.PointerEvent<SVGSVGElement>):[number,number]{const rect=e.currentTarget.getBoundingClientRect();return [Math.round(Math.max(0,Math.min(800,(e.clientX-rect.left)*800/rect.width))*10)/10,Math.round(Math.max(0,Math.min(1000,(e.clientY-rect.top)*1000/rect.height))*10)/10];}
 function down(e:React.PointerEvent<SVGSVGElement>){if(disabled||active.current||(e.pointerType==='mouse'&&e.button!==0))return;e.currentTarget.setPointerCapture(e.pointerId);const pan=e.pointerType==='touch'&&!finger;active.current={id:e.pointerId,stroke:null,before:strokes,erased:strokes,scrollY:e.clientY,pan};if(pan)return;e.preventDefault();setMessage('');if(tool==='eraser'){active.current.erased=strokes.filter(s=>s.page!==page||!hitsStroke(s,point(e)));onChange(active.current.erased);return;}if(strokes.length>=500||strokes.reduce((n,s)=>n+s.points.length,0)>=MAX_INK_POINTS){setMessage('필기 공간이 가득 찼어요. 새 차트에 이어서 작성해주세요.');active.current=null;return;}const stroke:InkStroke={id:crypto.randomUUID(),page,color,width,points:[point(e)]};active.current.stroke=stroke;setDraft(stroke);}
 function move(e:React.PointerEvent<SVGSVGElement>){const a=active.current;if(!a||a.id!==e.pointerId)return;if(a.pan){window.scrollBy(0,a.scrollY-e.clientY);a.scrollY=e.clientY;return;}e.preventDefault();const p=point(e);if(!a.stroke){a.erased=a.erased.filter(s=>s.page!==page||!hitsStroke(s,p));onChange(a.erased);return;}const points=a.stroke.points,last=points[points.length-1];if(Math.hypot(p[0]-last[0],p[1]-last[1])<1)return;if(points.length>=4096||a.before.reduce((n,s)=>n+s.points.length,0)+points.length>=MAX_INK_POINTS){setMessage('한 획의 길이 제한에 도달했어요. 펜을 떼고 이어서 작성해주세요.');return;}a.stroke={...a.stroke,points:[...points,p]};setDraft(a.stroke);}
 function end(e:React.PointerEvent<SVGSVGElement>){const a=active.current;if(!a||a.id!==e.pointerId)return;active.current=null;setDraft(null);if(a.pan)return;if(a.stroke)commit([...a.before,a.stroke],a.before);else if(a.erased.length!==a.before.length)commit(a.erased,a.before);}
 function undo(){if(!history.length)return;const last=history[history.length-1];setRedo(r=>[...r,strokes]);setHistory(h=>h.slice(0,-1));onChange(last);}
 function forward(){if(!redo.length)return;setHistory(h=>[...h,strokes]);onChange(redo[redo.length-1]);setRedo(r=>r.slice(0,-1));}
 return <section className="ink-editor"><div className="mode-switch ink-pages"><button type="button" aria-pressed={page==='sheet'} onClick={()=>setPage('sheet')}>필기 작업표</button><button type="button" aria-pressed={page==='ball'} onClick={()=>setPage('ball')}>볼 그림</button></div><fieldset className="ink-toolbar" disabled={disabled}><button type="button" aria-label="펜" aria-pressed={tool==='pen'} onClick={()=>setTool('pen')}><Pencil size={19}/></button><button type="button" aria-label="획 지우개" aria-pressed={tool==='eraser'} onClick={()=>setTool('eraser')}><Eraser size={19}/></button><span className="tool-divider"/>{INK_COLORS.map(v=><button key={v} type="button" aria-label={{'#203d38':'검정','#247a64':'초록','#326cc7':'파랑','#ce5160':'빨강'}[v]+' 펜'} aria-pressed={color===v} onClick={()=>{setColor(v);setTool('pen');}}><span className="ink-swatch" style={{background:v}}/></button>)}<select aria-label="펜 굵기" value={width} onChange={e=>setWidth(Number(e.target.value))}><option value={2}>가는 선</option><option value={3}>보통</option><option value={6}>굵은 선</option></select><button type="button" aria-label="실행 취소" disabled={!history.length||disabled} onClick={undo}><Undo2 size={19}/></button><button type="button" aria-label="다시 실행" disabled={!redo.length||disabled} onClick={forward}><Redo2 size={19}/></button><button type="button" aria-label="이 페이지 필기 지우기" onClick={()=>{if(strokes.some(s=>s.page===page)&&window.confirm('이 페이지의 필기를 모두 지울까요?'))commit(strokes.filter(s=>s.page!==page));}}><Trash2 size={19}/></button><button type="button" className="finger-toggle" aria-pressed={finger} onClick={()=>setFinger(!finger)}><Hand size={17}/>{finger?'손가락 필기':'펜슬 전용'}</button></fieldset><p className="ink-help">{finger?'손가락·펜슬로 필기할 수 있어요. 화면 이동은 필기 영역 바깥에서 해주세요.':'펜슬·마우스로 필기하고, 손가락으로 위아래 이동하세요.'} 지우개는 획 전체를 지웁니다.</p>{message&&<p className="login-error" role="status">{message}</p>}<InkSurface page={page} strokes={draft?[...strokes,draft]:strokes} onPointerDown={down} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onLostPointerCapture={end} style={{touchAction:'none',userSelect:'none',WebkitUserSelect:'none'}}/><p className="ink-help">필기는 아래 ‘작업표 저장’을 눌러 저장해요. 수치 입력과 필기는 따로 유지됩니다.</p></section>;
}
