'use client';
import { useEffect, useRef, useState } from 'react';
import { CircleDot, Plus, Save, Users, ChevronRight, Search, Printer, FileText } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Toaster, toast } from 'sonner';
import {InkBoard,InkPrint} from './ink-board';
import { Ball } from './ball-preview';
import { WorkSheet } from './work-sheet';
import { Chart, Hole, Measure, chartSchema, emptyChart, normalizeChart, parseInches, formatInches as f, missingSpecs } from '@/lib/drill-chart';
function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:string[][];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
function Inch({label,value,onChange,min=-2,max=7,unit='in',fractions=true}:{label:string;value:Measure;onChange:(v:Measure)=>void;min?:number;max?:number;unit?:string;fractions?:boolean}){
 const [raw,setRaw]=useState(value===null?'':String(value));const [err,setErr]=useState('');const input=useRef<HTMLInputElement>(null);const emitted=useRef<Measure|undefined>(undefined);
 useEffect(()=>{if(emitted.current===value)return;setRaw(value===null?'':String(value));setErr('');input.current?.setCustomValidity('');},[value]);
 function update(text:string){setRaw(text);try{const n=parseInches(text);if(n!==null&&(n<min||n>max))throw Error(`${min}〜${max} ${unit} 범위로 입력하세요.`);setErr('');input.current?.setCustomValidity('');emitted.current=n;onChange(n);}catch(e){const msg=(e as Error).message;setErr(msg);input.current?.setCustomValidity(msg);}}
 return <label className="precise-input"><span>{label}</span><div><input ref={input} aria-label={label} aria-invalid={!!err} value={raw} placeholder={fractions?'예: 7/8':'미입력'} onChange={e=>update(e.target.value)}/><small>{unit}</small></div><span className={err?'input-error':'input-equivalent'}>{err|| (value===null?'미입력':fractions?`${f(value)}″ · ${value} in`:String(value)+' '+unit)}</span></label>
}
function Text({label,value,onChange,max=120,placeholder=''}:{label:string;value:string;onChange:(s:string)=>void;max?:number;placeholder?:string}){return <label>{label}<input value={value} maxLength={max} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
const holeNames={middle:'중지',ring:'약지',thumb:'엄지'};
function Pitch({axis,value,onChange}:{axis:'forward'|'lateral';value:Measure;onChange:(n:Measure)=>void}){const [direction,setDirection]=useState(value!==null&&value<0?-1:1);useEffect(()=>{if(value!==null&&value!==0)setDirection(value<0?-1:1);},[value]);const sign=direction;return <div className="pitch-input"><Inch label={axis==='forward'?'전후 피치':'좌우 피치'} value={value===null?null:Math.abs(value)} onChange={n=>onChange(n===null?null:n*sign)} min={0} max={2}/><Choice label={axis==='forward'?'전후 방향':'좌우 방향'} value={String(sign)} onChange={s=>{setDirection(Number(s));if(value!==null)onChange(Math.abs(value)*Number(s));}} items={axis==='forward'?[['1','F · 포워드'],['-1','R · 리버스']]:[['1','오른쪽'],['-1','왼쪽']]}/></div>}
export default function Home({onLogout,onAccount,accountLabel}:{onLogout:()=>void;onAccount:()=>void;accountLabel:string}){
 const [inputMode,setInputMode]=useState<'numbers'|'ink'>('numbers');const [listOpen,setListOpen]=useState(false);
 const [c,setC]=useState<Chart>(emptyChart);const [list,setList]=useState<Chart[]>([]);const [dirty,setDirty]=useState(false);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');const [view,setView]=useState('work');const [hole,setHole]=useState<'middle'|'ring'|'thumb'>('middle');const form=useRef<HTMLFormElement>(null);
 const change=<K extends keyof Chart>(key:K,v:Chart[K])=>{setC(p=>({...p,[key]:v}));setDirty(true);};const spec=<K extends keyof Chart['spec']>(key:K,v:Chart['spec'][K])=>change('spec',{...c.spec,[key]:v});
 async function load(){setLoading(true);setError('');try{const res=await fetch('/api/charts');const data=await res.json() as Chart[]&{error?:string};if(!res.ok)throw Error(data.error);setList(data.map(normalizeChart));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
 function choose(next:Chart){if(dirty&&!window.confirm('저장하지 않은 변경 사항을 버릴까요?'))return;setC(next);setListOpen(false);setDirty(false);setHole('middle');}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{const res=await fetch('/api/charts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...c,id:c.id||crypto.randomUUID()})});const d=await res.json() as Chart&{error?:string};if(!res.ok)throw Error(d.error);setC(normalizeChart(d));setList(p=>[normalizeChart(d),...p.filter(x=>x.id!==d.id)]);setDirty(false);toast.success('작업표를 저장했어요.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 const active=c[hole];const holes=(Object.keys(holeNames) as ('middle'|'ring'|'thumb')[]).filter(k=>c.grip!=='two'||k!=='thumb');const groups=Array.from(new Set(list.filter(x=>(x.name+' '+x.ball).toLowerCase().includes(query.toLowerCase())).map(x=>x.name)));const missing=missingSpecs(c);
 const preview={...c,middleSpan:c.middleSpan??NaN,ringSpan:c.ringSpan??NaN,bridge:c.bridge??NaN,...Object.fromEntries(['middle','ring','thumb'].map(k=>[k,Object.fromEntries(Object.entries(c[k as 'middle']).map(([f,v])=>[f,v??NaN]))]))} as unknown as Parameters<typeof Ball>[0]['c'];
 function print(){if(!form.current?.reportValidity())return;const checked=chartSchema.safeParse({...c,id:c.id||crypto.randomUUID()});if(!checked.success){toast.error(checked.error.issues[0]?.message||'작업 수치를 확인해주세요.');return;}window.print();}
 return <><div className="app-shell"><Toaster richColors position="top-center"/><header className="topbar"><a href="/" className="brand"><span className="brand-icon"><CircleDot size={24}/></span>FIT<span className="brand-light">STUDIO</span><span className="edition">PRO SHOP</span></a><span className="header-note">{accountLabel}</span><button type="button" className="logout-button" onClick={()=>{if(!dirty||window.confirm("저장하지 않은 변경 사항을 버리고 계정 관리로 이동할까요?"))onAccount();}}>계정 관리</button><button type="button" className="logout-button" onClick={()=>{if(!dirty||window.confirm("저장하지 않은 변경 사항을 버리고 로그아웃할까요?"))onLogout();}}>로그아웃</button></header><div className={'workspace '+(listOpen?'list-open':'')}><aside className="people"><div className="aside-title"><Users size={17}/> 볼러 & 차트 <span>{new Set(list.map(x=>x.name)).size}</span></div><button type="button" className="new-chart" disabled={busy} onClick={()=>choose(emptyChart())}><Plus size={17}/>새 지공차트</button><div className="search"><Search size={15}/><input aria-label="이름 또는 볼 검색" placeholder="이름 또는 볼 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="people-list">{loading?<p className="empty">차트를 불러오는 중…</p>:error?<div className="empty"><p>{error}</p><button onClick={load}>다시 불러오기</button></div>:groups.length?groups.map(name=><div className="person-group" key={name}><h3><span className="avatar">{name.slice(0,1)}</span>{name}</h3>{list.filter(x=>x.name===name&&(x.name+' '+x.ball).toLowerCase().includes(query.toLowerCase())).map(x=><button disabled={busy} className={'chart-item '+(c.id===x.id?'selected':'')} key={x.id} onClick={()=>choose(x)}><span><strong>{x.ball||'기본 지공차트'}</strong><small>{x.updated?.slice(0,10)} · {x.hand==='right'?'오른손':'왼손'}</small></span><ChevronRight size={14}/></button>)}</div>):<div className="empty"><CircleDot size={30}/><p>{query?'검색 결과가 없어요.':'저장된 차트가 없어요.'}</p></div>}</div><div className="aside-footer"><FileText size={23}/><span>프로숍 작업표<br/>inch · 1/64 · A4</span></div></aside><main><div className="page-heading"><div><div className="eyebrow">PRO SHOP WORKSPACE</div><h1>볼링 지공차트</h1><p>실측 수치를 기록하고, 지공 작업표로 출력하세요.</p></div><div className={'save-state '+(dirty?'unsaved':'')}><span/>{dirty?'저장 전 변경 사항':c.id?'저장된 차트':'새 작업표'}</div></div>
 <div className="editor-nav"><button type="button" className="list-toggle" onClick={()=>setListOpen(!listOpen)}><Users size={17}/>{listOpen?'목록 닫기':'차트 선택'} · {list.length}</button><div className="mode-switch" aria-label="작성 모드"><button type="button" aria-pressed={inputMode==='numbers'} onClick={()=>setInputMode('numbers')}>수치 입력</button><button type="button" aria-pressed={inputMode==='ink'} onClick={()=>setInputMode('ink')}>✎ 자유 필기</button></div></div><form ref={form} onSubmit={save} className={inputMode==='ink'?'handwriting-mode':''}>{inputMode==='ink'&&<><div className="panel ink-identity form-grid"><label>볼러 이름 *<input required maxLength={80} value={c.name} onChange={e=>change('name',e.target.value)} placeholder="이름"/></label><label>볼 이름<input maxLength={100} value={c.ball} onChange={e=>change('ball',e.target.value)} placeholder="볼 이름"/></label></div><InkBoard key={c.id||'new'} strokes={c.ink||[]} onChange={v=>change('ink',v)} disabled={busy}/></>}<fieldset disabled={busy||inputMode==='ink'} className="editor-fieldset"><div className="editor-grid standard-grid"><div className="form-column" key={c.id||'new'}>
 <section className="panel"><div className="section-title"><span>01</span><h2>볼러 & 볼 정보</h2></div><div className="form-grid"><label>이름 *<input required maxLength={80} placeholder="볼러 이름" value={c.name} onChange={e=>change('name',e.target.value)}/></label><Text label="볼 이름" value={c.ball} max={100} onChange={v=>change('ball',v)}/><label>사용 손<Choice value={c.hand} onChange={v=>change('hand',v as Chart['hand'])} label="사용 손" items={[["right","오른손"],["left","왼손"]]}/></label><label>그립 방식<Choice value={c.grip} onChange={v=>{change('grip',v as Chart['grip']);if(v==='two')setHole('middle');}} label="그립 방식" items={[["finger","핑거팁"],["conventional","컨벤셔널"],["two","엄지 없음"]]}/></label><label>작업 날짜<input type="date" required value={c.spec.date} onChange={e=>spec('date',e.target.value)}/></label><Text label="작업자 / 프로숍" value={c.spec.driller} max={100} onChange={v=>spec('driller',v)}/><Inch label="볼 무게" value={c.spec.weight} onChange={v=>spec('weight',v)} min={1} max={20} unit="lb" fractions={false}/><Text label="시리얼 번호" value={c.spec.serial} max={100} onChange={v=>spec('serial',v)}/></div></section>
 <section className="panel"><div className="section-title"><span>02</span><h2>스팬 & 브리지</h2><small>inch</small></div>{c.grip!=='two'&&<><label>스팬 측정 기준<Choice label="스팬 측정 기준" value={c.spec.spanBasis} onChange={v=>spec('spanBasis',v as Chart['spec']['spanBasis'])} items={[["cut","Cut-to-cut · 절삭 홀 가장자리"],["finished","Finished · 마감 접촉 가장자리"],["unknown","미지정 · 확인 필요"]]}/></label><p className="standalone-help">Cut-to-cut은 베벨 전 절삭 홀의 가까운 가장자리 간 표면 측정값입니다. 인서트 보정이나 중심 간 거리로 자동 변환하지 않습니다.</p><div className="form-grid"><Inch label="중지 스팬" value={c.middleSpan} onChange={v=>change('middleSpan',v)} min={.01}/><Inch label="약지 스팬" value={c.ringSpan} onChange={v=>change('ringSpan',v)} min={.01}/></div></>}<Inch label="브리지 · 절삭 홀 가장자리 간" value={c.bridge} onChange={v=>change('bridge',v)} min={.01} max={2}/><p className="standalone-help">입력 예: 4 3/8, 7/8, 0.015625. 빈칸과 0은 구분해서 저장합니다.</p></section>
 <section className="panel"><div className="section-title"><span>03</span><h2>홀 규격 & 피치</h2><small>inch</small></div><Tabs value={hole} onValueChange={v=>{const bad=form.current?.querySelector<HTMLInputElement>('[aria-invalid="true"]');if(bad){bad.reportValidity();return;}setHole(v as typeof hole);}}><TabsList className="hole-tabs">{holes.map(k=><TabsTrigger value={k} key={k}>{holeNames[k]}</TabsTrigger>)}</TabsList></Tabs><div key={hole} className="form-grid"><Inch label="드릴 외경" value={active.diameter} onChange={v=>change(hole,{...active,diameter:v})} min={.01} max={2}/><Inch label="홀 깊이" value={active.depth} onChange={v=>change(hole,{...active,depth:v})} min={.01} max={4}/><Pitch axis="forward" value={active.forward} onChange={v=>change(hole,{...active,forward:v})}/><Pitch axis="lateral" value={active.lateral} onChange={v=>change(hole,{...active,lateral:v})}/><Text label="인서트 종류 / 모델" value={active.insertStyle} onChange={v=>change(hole,{...active,insertStyle:v})} placeholder="없으면 '없음'"/><Text label="인서트 사이즈" value={active.insertSize} onChange={v=>change(hole,{...active,insertSize:v})}/></div><Text label="베벨" value={active.bevel} onChange={v=>change(hole,{...active,bevel:v})} placeholder="크기 / 각도 / 마감 방식"/><p className="standalone-help">피치는 inch 게이지 값입니다. 0은 중립이며, F는 그립 중앙 쪽, R은 그 반대입니다. 좌우는 볼 표면을 바라본 방향입니다.</p><Text label="피치 게이지 / 장비 기준" value={c.spec.pitchReference} max={200} onChange={v=>spec('pitchReference',v)} placeholder="사용 게이지·장비명과 기준을 기록"/><Text label="홀 깊이 측정 기준" value={c.spec.depthReference} max={200} onChange={v=>spec('depthReference',v)}/></section>
 {c.grip!=='two'&&<section className="panel"><div className="section-title"><span>04</span><h2>엄지 형상</h2></div><label>마감 형상<Choice label="엄지 마감 형상" value={c.spec.ovalShape} onChange={v=>spec('ovalShape',v as Chart['spec']['ovalShape'])} items={[["round","원형"],["oval","타원"],["unknown","미지정"]]}/></label>{c.spec.ovalShape==='oval'&&<><div className="form-grid"><Inch label="마감 장축" value={c.spec.ovalLong} onChange={v=>spec('ovalLong',v)} min={.01} max={2}/><Inch label="마감 단축" value={c.spec.ovalShort} onChange={v=>spec('ovalShort',v)} min={.01} max={2}/><Inch label="타원 각도" value={c.spec.ovalAngle} onChange={v=>spec('ovalAngle',v)} min={0} max={180} unit="°" fractions={false}/></div><Text label="타원 각도 기준" value={c.spec.ovalReference} onChange={v=>spec('ovalReference',v)} max={200}/><p className="standalone-help">마감 타원 치수입니다. 드릴경과 별도로 기록하며, X/Y 테이블 이동량으로 자동 환산하지 않습니다.</p></>}</section>}
 <section className="panel"><div className="section-title"><span>05</span><h2>PAP & 레이아웃</h2></div><div className="form-grid"><Inch label="PAP 수평 · 오른쪽 + / 왼쪽 −" value={c.spec.papHorizontal} onChange={v=>spec('papHorizontal',v)} min={-10} max={10}/><Inch label="PAP 수직 · 위 + / 아래 −" value={c.spec.papVertical} onChange={v=>spec('papVertical',v)} min={-10} max={10}/></div><Text label="레이아웃 · 방식과 수치를 함께 기록" value={c.spec.layout} onChange={v=>spec('layout',v)} max={300} placeholder="예: Dual angle 50° × 4 1/2″ × 35°"/><Text label="표면 마감" value={c.spec.finish} onChange={v=>spec('finish',v)} max={200}/><label>작업 메모<textarea rows={3} maxLength={3000} value={c.notes} onChange={e=>change('notes',e.target.value)} placeholder="피팅 특이사항, 측정 도구, 장비별 보정 등을 기록"/></label></section>
 </div><div className="preview-column work-preview"><Tabs value={view} onValueChange={setView}><TabsList className="preview-switch"><TabsTrigger value="work"><FileText size={15}/>작업표</TabsTrigger><TabsTrigger value="front">볼 정면</TabsTrigger><TabsTrigger value="angle">볼 사선</TabsTrigger></TabsList></Tabs>{view==='work'?<WorkSheet c={c} dirty={dirty}/>:<><section className="preview-panel"><div className="preview-heading"><div>POSITION REFERENCE<h2>지공 위치 미리보기</h2></div></div><Ball c={preview} view={view}/></section><p className="standalone-help">볼 미리보기는 근사 위치도입니다. 미입력 항목은 중립적인 예시 형상으로 표시됩니다. 실제 작업값은 작업표를 확인하세요.</p></>}
 <div className="work-status"><strong>{missing.length?`작성 중 · 주요 항목 ${missing.length}개 미입력`:'주요 항목 입력 완료'}</strong><p>{missing.length?missing.join(' · '):'입력 수치와 실측값을 대조한 뒤 작업하세요.'}</p></div><p className="source-note">항목 구성 참고: <a href="https://www.jayhawkbowling.com/Pro_s_Corner/Pro_Shop_Forms/balllayout.jpg.pdf" target="_blank" rel="noreferrer">Jayhawk 프로숍 차트</a> · <a href="https://www.jayhawkbowling.com/Pro_Shop_Manuals/jpegmanual.pdf" target="_blank" rel="noreferrer">Edge Gauge 측정 안내</a></p></div></div></fieldset>
 <div className="share-control"><label><Checkbox checked={c.shared??false} disabled={busy} onCheckedChange={v=>change('shared',v===true)}/> 누구나 이 차트 조회 가능</label><p>체크 후 저장한 차트만 로그인 없이 공개됩니다. 작업 메모를 포함한 전체 작업표가 공유됩니다.</p></div><footer className="editor-footer"><span>{dirty?'현재 변경 사항을 저장해주세요.':c.id?'저장된 작업표':'새 차트는 실측값으로 작성하세요.'}</span><div className="footer-actions"><button className="print-button" type="button" onClick={print} disabled={busy}><Printer size={17}/>A4 인쇄 / PDF</button><button className="save-button" type="submit" disabled={busy||loading}><Save size={17}/>{busy?'저장 중…':'작업표 저장'}</button></div></footer></form></main></div></div><div className="print-only"><WorkSheet c={c} dirty={dirty}/><InkPrint c={c}/></div></>;
}
