import {useEffect,useMemo,useRef,useState} from 'react';
import * as T from 'three';
import CoreViewer,{type ViewerProps,type SpinMotion} from './core-viewer';
import {BALL_RADIUS,coreGeometry,holeTools,subtractHoles} from '../lib/core-geometry';
import {meshInertia,relaxation} from '../lib/spin-physics';
export default function SpinLab({params:p}:{params:ViewerProps}){
 const [rpm,setRpm]=useState(240),[tilt,setTilt]=useState(55),[azimuth,setAzimuth]=useState(25),[density,setDensity]=useState(2),[damping,setDamping]=useState(1),[time,setTime]=useState(0),[running,setRunning]=useState(false);
 const motion=useRef<SpinMotion>({rotation:new T.Quaternion(),axis:new T.Vector3(0,1,0),trail:[],revision:0});
 const calculation=useMemo(()=>{if(!p.model||!p.valid)return null;const sphere=new T.SphereGeometry(BALL_RADIUS,48,32),core=coreGeometry({...p.settings,modelVersion:p.model}),tools=holeTools(p.settings,...p.diameters,p.bridge,p.left),mat=new T.MeshBasicMaterial();let sg:T.BufferGeometry|undefined,cg:T.BufferGeometry|undefined;try{const a=subtractHoles(sphere,tools,mat,mat),b=subtractHoles(core,tools,mat,mat);a.removed.forEach(x=>x.dispose());b.removed.forEach(x=>x.dispose());sg=a.result.geometry;cg=b.result.geometry;const baseSphere=meshInertia(sphere),sphereMoment=8*Math.PI*Math.pow(BALL_RADIUS,5)/15;const sum=(outer:T.BufferGeometry,inner:T.BufferGeometry)=>{const x=meshInertia(outer),y=meshInertia(inner);x.elements=x.elements.map((v,i)=>v-baseSphere.elements[i]+(i%4===0?sphereMoment:0)+(density-1)*y.elements[i]) as typeof x.elements;return x;};return {before:sum(sphere,core),after:sum(sg,cg)};}catch{return null;}finally{sphere.dispose();core.dispose();sg?.dispose();cg?.dispose();tools.forEach(x=>x.geometry.dispose());mat.dispose();}},[p.model,p.valid,p.settings,p.diameters,p.bridge,p.left,density]);
 const comparison=useMemo(()=>{if(!calculation)return null;const start=new T.Vector3().setFromSphericalCoords(1,T.MathUtils.degToRad(tilt),T.MathUtils.degToRad(azimuth));return {before:relaxation(calculation.before,start,damping),after:relaxation(calculation.after,start,damping)};},[calculation,tilt,azimuth,damping]);
 const result=p.drill?comparison?.after:comparison?.before,index=Math.min(480,Math.round(time*30)),frame=result?.frames[index];
 useEffect(()=>{setTime(0);setRunning(false);},[comparison,p.drill,rpm]);
 useEffect(()=>{if(!running)return;let id=0,last=performance.now();const tick=(now:number)=>{if(now-last>=50){const dt=Math.min(.1,(now-last)/1000);last=now;setTime(t=>{if(t+dt>=16){setRunning(false);return 16;}return t+dt;});}id=requestAnimationFrame(tick);};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id);},[running]);
 useEffect(()=>{if(!frame)return;const align=new T.Quaternion().setFromUnitVectors(frame.axis,new T.Vector3(0,1,0)),turn=new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),time*rpm/60*2*Math.PI*.15);motion.current.rotation.copy(turn.multiply(align));motion.current.axis.copy(frame.axis);motion.current.trail=result!.frames.slice(0,index+1).filter((_,i)=>i%8===0).map(f=>f.axis.clone().multiplyScalar(BALL_RADIUS+3));motion.current.revision++;},[frame,result,index,time,rpm]);
 if(!p.model||!p.valid)return <div className="lab-spin"><p>15 lb의 3D 지원 공을 선택하고, 덤리스·투핸드 드릴경과 브리지를 숫자로 입력해주세요.</p></div>;
 if(!result||!frame)return <div className="lab-spin" role="alert">이 형상의 관성을 계산하지 못했습니다. 다른 코어를 선택해주세요.</div>;
 const difference=comparison?.before.unique&&comparison.after.unique?T.MathUtils.radToDeg(Math.acos(Math.min(1,Math.abs(comparison.before.axes[2].axis.dot(comparison.after.axes[2].axis))))):null;
 return <><CoreViewer {...p} motion={motion.current}/><section className="lab-spin"><strong>회전 안정화 실험 · 가정 기반</strong><p>구 중심 고정 · 주변 재료 밀도 1 · 코어 상대 밀도 {density}. 제품 RG·Diff에 보정한 모델은 아닙니다. 에너지 감소 모형이며 실제 장비의 마찰·안정 시간·PSA를 예측하지 않습니다. RPM은 화면 회전에만 적용되며 0.15배속으로 보여줍니다.</p><div className="lab-spin-actions"><button onClick={()=>{if(time>=16)setTime(0);setRunning(v=>!v);}}>{running?'일시정지':time>=16?'다시 돌리기':'돌리기'}</button><button onClick={()=>{setRunning(false);setTime(0);}}>처음으로</button><span role="status">{frame.angle<2?'안정 영역에 도달':time>=16?'재생 종료 · 미수렴':'축 이동 관찰'} · {frame.angle.toFixed(1)}°</span></div><label>재생 위치 {time.toFixed(1)} / 16<input aria-label="회전 재생 위치" type="range" min="0" max="16" step=".1" value={time} onChange={e=>{setRunning(false);setTime(Number(e.target.value));}}/></label><p>흰 선: 현재 회전축 · 주황 점: 공 표면의 축 이동 경로. {result.unique?'가정 모델에서 안정축 1개(양 끝은 같은 축).':'안정 방향이 여러 개여서 특정 PSA 한 점으로 지정할 수 없습니다.'} 지공 전·후 안정축 차이: {difference===null?'단일 축 비교 불가':difference.toFixed(1)+'° (추정)'}.</p><details><summary>시작 조건과 가정 변경</summary><div className="lab-spin-grid">{[{label:'초기 회전수 (RPM)',value:rpm,set:setRpm,min:60,max:600,step:10},{label:'시작 축 기울기 (°)',value:tilt,set:setTilt,min:0,max:180,step:1},{label:'시작 축 방위 (°)',value:azimuth,set:setAzimuth,min:-180,max:180,step:1},{label:'코어 상대 밀도',value:density,set:setDensity,min:1,max:5,step:.1},{label:'가정 감쇠 강도',value:damping,set:setDamping,min:0,max:2,step:.1}].map(x=><label key={x.label}>{x.label} <output>{x.value}</output><input aria-label={x.label} type="range" value={x.value} min={x.min} max={x.max} step={x.step} onChange={e=>x.set(Number(e.target.value))}/></label>)}</div></details><p>같은 시작 조건에서 위의 ‘지공 전 / 후’를 전환해 비교하세요. 이 실험의 설정은 차트에 저장하지 않습니다.</p></section></>;
}
