import {lazy,Suspense,useEffect,useMemo,useState,useDeferredValue} from 'react';
import {ArrowLeft,Box,ChevronDown,Rotate3D,Save,Search,Sparkles} from 'lucide-react';
import {brands,emptyCatalog,releaseBadge,modelFor,coreModels,type CoreModelId,type Catalog} from '../lib/ball-catalog';
import {defaultSimulation,numericMm,type Simulation} from '../lib/simulation';
import {emptyChart,normalizeChart,parseMeasureInput,hasThumb,type Chart} from '../lib/drill-chart';
import {WorkSheet} from './work-sheet';
import './test-lab.css';
import referenceData from '../lib/catalog-reference.json';
import type {BallProduct} from '../lib/ball-catalog';
const references=referenceData as Record<string,{specs:NonNullable<BallProduct['specs']>;source:string;checkedAt:string}>;
const Viewer=lazy(()=>import('./core-viewer'));
function example(){const c=emptyChart();return {...c,hand:'left' as const,grip:'thumbless' as const,bridge:.375,middle:{...c.middle,diameter:1.03125},ring:{...c.ring,diameter:1.03125},simulation:defaultSimulation()};}
export default function TestLab(){
const [panel,setPanel]=useState<'catalog'|'view'|'settings'>('view');
const [compact,setCompact]=useState(()=>window.matchMedia('(max-width:800px)').matches);
useEffect(()=>{const media=window.matchMedia('(max-width:800px)');const update=()=>setCompact(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);

const [catalog,setCatalog]=useState<Catalog>(emptyCatalog),[brand,setBrand]=useState('storm'),[query,setQuery]=useState(''),[onlyModels,setOnlyModels]=useState(false),[c,setC]=useState<Chart>(example),[s,setS]=useState<Simulation>(defaultSimulation),[charts,setCharts]=useState<Chart[]>([]),[canSave,setCanSave]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[catalogError,setCatalogError]=useState(''),[loading,setLoading]=useState(true),[drill,setDrill]=useState(true),[removed,setRemoved]=useState(false),[view,setView]=useState<'grip'|'core'>('grip'),[opacity,setOpacity]=useState(.13),[exampleMode,setExampleMode]=useState(true);
useEffect(()=>{let alive=true;Promise.allSettled([fetch('/.netlify/functions/catalog').then(r=>{if(!r.ok)throw Error();return r.json();}),fetch('/api/charts').then(r=>{if(!r.ok)throw Error();return r.json();}),fetch('/api/session').then(r=>{if(!r.ok)throw Error();return r.json();})]).then(([cat,list,session])=>{if(!alive)return;if(cat.status==='fulfilled'){setCatalog(cat.value);if(!cat.value.available)setCatalogError('목록 연결 실패 · 기본 목록으로 시작합니다.');}else setCatalogError('목록 연결 실패 · 기본 목록으로 시작합니다.');if(list.status==='fulfilled')setCharts(list.value.map(normalizeChart));else setMessage('저장된 차트를 불러오지 못했습니다. 새로고침해주세요.');if(session.status==='fulfilled')setCanSave(['editor','admin'].includes(session.value.user?.role));setLoading(false);});return()=>{alive=false;};},[]);
useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
const product=catalog.products.find(p=>p.id===s.productId);const model=modelFor(product,s.weight);const dimensions=[numericMm(c.middle.diameter),numericMm(c.ring.diameter),numericMm(c.bridge)];const valid=dimensions.every(v=>v!==null&&v>0)&&!hasThumb(c.grip);const d1=dimensions[0]??26.2,d2=dimensions[1]??26.2,bridge=dimensions[2]??9.525;
const params=useMemo(()=>({settings:s,diameters:[d1,d2] as [number,number],bridge,left:c.hand==='left',model,valid,drill:drill&&valid,view,showRemoved:removed,shellOpacity:opacity}),[s,d1,d2,bridge,c.hand,model,drill,valid,view,removed,opacity]);const deferred=useDeferredValue(params);
const shown=catalog.products.filter(p=>p.brand===brand&&(!onlyModels||!!modelFor(p,15))&&(p.name+' '+p.core).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(b.releaseDate??'').localeCompare(a.releaseDate??''));
const coreGroups=[...new Map(catalog.products.map(p=>[p.brand+'/'+p.coreKey,{...p,count:catalog.products.filter(x=>x.brand===p.brand&&x.coreKey===p.coreKey).length}])).values()];
const reference=product?references[product.id]:undefined;const spec=product?.specs?.[s.weight]??reference?.specs?.[s.weight];
function update(next:Chart){setC(next);setDirty(true);setMessage('');}
function setting<K extends keyof Simulation>(key:K,value:Simulation[K]){setS(p=>({...p,[key]:value}));setDirty(true);setMessage('');}
function choose(id:string){setPanel('view');const p=catalog.products.find(p=>p.id===id);if(!p)return;setS(v=>({...v,productId:p.id,weight:p.weights.includes(v.weight)?v.weight:p.weights[0]??15}));setC(v=>({...v,ball:p.name}));setDirty(true);setMessage('');}
function loadChart(id:string){const next=charts.find(x=>x.id===id);if(!next)return;if(dirty&&!confirm('현재 변경 사항을 버리고 차트를 불러올까요?'))return;setC(next);const matched=catalog.products.find(p=>p.name.toLowerCase()===next.ball.toLowerCase());const sim=next.simulation??{...defaultSimulation(),productId:matched?.id??'',weight:typeof next.spec.weight==='number'?Math.round(next.spec.weight):15};setS(sim);setBrand(catalog.products.find(p=>p.id===sim.productId)?.brand??'storm');setDirty(false);setExampleMode(false);setMessage(next.simulation?'저장한 시뮬레이션을 불러왔습니다.':'차트 수치를 불러왔습니다. 깊이·코어 방향·각도는 예시값이므로 확인해주세요.');}
async function save(){if(!product){setMessage('공을 선택해주세요.');return;}if(!c.name.trim()){setMessage('저장할 볼러 이름을 입력해주세요.');return;}setBusy(true);try{const next={...c,id:c.id||crypto.randomUUID(),ball:product.name,spec:{...c.spec,weight:s.weight},simulation:{...s,modelVersion:model}};const res=await fetch('/api/charts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});const data=await res.json();if(!res.ok)throw Error(data.error||'저장 실패');const saved=normalizeChart(data);setC(saved);setCharts(p=>[saved,...p.filter(x=>x.id!==saved.id)]);setDirty(false);setExampleMode(false);setMessage('차트와 3D 설정을 함께 저장했습니다.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
return <main className="core-lab" data-panel={panel}><header className="lab-top"><a href="/"><ArrowLeft size={17}/> 지공차트</a><span>FIT STUDIO <b>LAB</b></span><span className="lab-path">/test</span></header>
<section className="lab-heading"><div><span className="lab-eyebrow">CORE & DRILLING</span><h1>내 지공을, 더 선명하게.</h1><p>공과 코어를 선택하고 내 지공을 비교하세요.</p></div><div className="lab-heading-icon"><Rotate3D size={36}/></div></section>
<nav className="lab-mobile-nav" aria-label="작업 화면">{([['catalog','공 선택'],['view','3D 보기'],['settings','지공 설정']] as const).map(([id,label])=><button key={id} type="button" aria-pressed={panel===id} onClick={()=>setPanel(id)}>{label}</button>)}</nav><div className="lab-layout"><aside className="lab-catalog"><div className="lab-section-title"><Box size={18}/><h2>볼 선택</h2><span>{catalog.products.length}</span></div><label className="lab-field">브랜드<select value={brand} onChange={e=>{setBrand(e.target.value);setQuery('');}}>{brands.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="lab-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="공·코어 이름 검색" aria-label="공·코어 이름 검색"/></label>
<label className="lab-model-filter"><input type="checkbox" checked={onlyModels} onChange={e=>setOnlyModels(e.target.checked)}/>3D 코어 지원 공만 · 15 lb</label><div className="lab-product-list">{shown.length?shown.map(p=>{const badge=releaseBadge(p.releaseDate);return <button className={'lab-product '+(s.productId===p.id?'selected':'')} key={p.id} onClick={()=>choose(p.id)}><span className="lab-ball-icon"><Box size={19}/></span><span><strong>{p.name}</strong><small>{p.core}{modelFor(p,15)&&<em className="lab-model-badge">3D</em>}</small></span>{badge&&<b className="lab-new">{badge}</b>}</button>}):<p className="lab-empty">{loading?'목록을 불러오는 중…':'현재 수집된 공이 없습니다.'}</p>}</div>
<details className="lab-core-directory"><summary>코어 도감 · {coreGroups.length}종</summary><p>현재 브랜드의 코어 · 사용 제품 수</p><div>{coreGroups.filter(p=>p.brand===brand).sort((a,b)=>b.count-a.count).map(p=><button key={p.coreKey} onClick={()=>{choose(p.id);setQuery(p.core);setOnlyModels(false);}}><strong>{p.core}</strong><span>{p.count}개 · {modelFor(p,15)?'3D':'정보'}</span></button>)}</div></details><details className="lab-sync"><summary>제품 정보 갱신 <ChevronDown size={13}/></summary><p>매일 오전 6시(한국) · 브랜드별 최신·이전 출시 제품을 차례로 갱신</p><p>NEW는 확인된 출시일로부터 60일. 출시일이 없으면 표시하지 않습니다.</p><p>마지막 수집: {catalog.lastSuccess?new Date(catalog.lastSuccess).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'아직 실행 전'}</p>{catalogError&&<p>{catalogError}</p>}{catalog.errors.length>0&&<p>일부 수집 실패 · 이전 정보를 유지합니다. ({catalog.errors.length}건)</p>}<a href="https://www.bowwwl.com/bowling-ball-database" target="_blank" rel="noreferrer">제품 정보 출처: bowwwl</a></details></aside>
<section className="lab-workspace"><div className="lab-view-card"><div className="lab-view-title"><div><span>{product?brands.find(([b])=>b===product.brand)?.[1]:'공 선택 필요'}</span><h2>{product?.name??'차트에 연결할 공을 선택하세요'}</h2></div><label className="lab-weight">무게<select value={s.weight} onChange={e=>setting('weight',Number(e.target.value))}>{(product?.weights??[15]).map(w=><option value={w} key={w}>{w} lb</option>)}</select></label></div>
<label className="lab-core-picker">코어 바로 보기 · {Object.keys(coreModels).length}종<select aria-label="코어 바로 보기" value={model??''} onChange={e=>{const id=e.target.value as CoreModelId;const match=catalog.products.find(p=>modelFor(p,15)===id);if(match){setBrand(match.brand);choose(match.id);setS(v=>({...v,weight:15}));}}}><option value="" disabled>코어 선택</option>{(Object.keys(coreModels) as CoreModelId[]).map(id=><option value={id} key={id} disabled={!catalog.products.some(p=>modelFor(p,15)===id)}>{coreModels[id].name}</option>)}</select></label><div className="lab-view-tabs"><button className={view==='grip'?'active':''} onClick={()=>setView('grip')}>그립 기준</button><button className={view==='core'?'active':''} onClick={()=>setView('core')}>코어 입체</button><button className={!drill?'active':''} onClick={()=>setDrill(v=>!v)}>{drill?'지공 후':'지공 전'}</button></div>
{(!compact||panel==='view')&&<Suspense fallback={<div className="lab-viewport lab-empty">3D 엔진 불러오는 중…</div>}><Viewer {...deferred}/></Suspense>}
<div className="lab-view-caption"><span>중지: 민트 · 약지: 보라 · 드래그 회전</span><span>{c.hand==='left'?'왼손':'오른손'} · {hasThumb(c.grip)?'엄지 사용 차트':'엄지 없는 2홀'}</span></div>
<div className="lab-view-controls"><label>외피<input aria-label="외피 불투명도" type="range" min="0" max=".5" step=".01" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label><label><input type="checkbox" checked={removed} onChange={e=>setRemoved(e.target.checked)}/>잘린 코어 표시</label></div>
<details className="lab-model-disclosure"><summary>모델 정확도와 참고 자료</summary><p className="lab-model-note">{model?`${coreModels[model].name} · 공식 이미지를 참고한 추정 형상입니다. ${model==='c3-v1'?'단면 그림 비율(폭 63%·높이 80%).':'크기는 시각화용 가정값입니다.'} ${model.includes('-ai-')?'중심 코어 형상만 표시하며 A.I. 외핵은 아직 생략했습니다. ':''}실제 지공 판단용 도면이 아닙니다.`:'이 코어·무게는 3D 모델 준비 전입니다. 공과 구멍만 표시합니다.'}</p>{model&&<a className="lab-core-source" href={`https://stormproducts.nyc3.cdn.digitaloceanspaces.com/web_page_content/weightblock-web-page/weightblocks/${coreModels[model].image}`} target="_blank" rel="noreferrer">코어 원본 이미지 보기 ↗</a>}</details>{!valid&&<p className="lab-warning">{hasThumb(c.grip)?'현재 3D는 덤리스·투핸드 2홀만 지원합니다.':'드릴경과 브리지를 숫자로 입력하면 지공 형상을 볼 수 있습니다. 한글 메모는 계산하지 않습니다.'}</p>}
</div>
<section className="lab-settings"><details className="lab-detail lab-specs"><summary>코어 정보 · {product?.core??'공 선택 필요'}</summary><div className="lab-spec-grid"><div><small>무게</small><strong>{s.weight} lb</strong></div><div><small>RG (inch)</small><strong>{spec?.rg?.toFixed(3)??'미확인'}</strong></div><div><small>Diff</small><strong>{spec?.diff?.toFixed(3)??'미확인'}</strong></div><div><small>중간 Diff</small><strong>{spec?.intermediate?.toFixed(3)??'미확인'}</strong></div></div><p>제품의 지공 전 제원입니다. 지공 후 변화량은 계산하지 않습니다. 자료에 없는 수치를 0으로 채우지 않습니다.</p>{product&&<a href={product.source} target="_blank" rel="noreferrer">제품 제원 출처 · bowwwl ↗</a>}{reference&&<p>제원 확인: {new Date(product?.specs?product.checkedAt??reference.checkedAt:reference.checkedAt).toLocaleDateString('ko-KR')}</p>}{model&&<p>{['atomic-ai-v1','momentous-ai-v1','nucleus-ai-v1','disturbance-ai-v1','ellipse-ai-v1','supercoil-v1'].includes(model)?'복합 형상의 개략 모델입니다. 보이지 않는 두께·홈·모서리는 가정값이며 실제 PSA 방향을 나타내지 않습니다.':'이미지 실루엣 기반 추정 모델입니다.'}</p>}</details><div className="lab-section-title"><Sparkles size={18}/><h2>지공 설정</h2>{exampleMode&&<span>예시값</span>}</div><div className="lab-fields"><label className="lab-field">저장된 차트<select value={c.id} onChange={e=>loadChart(e.target.value)}><option value="">차트 불러오기</option>{charts.map(x=><option key={x.id} value={x.id}>{x.name} · {x.ball}</option>)}</select></label><label className="lab-field">볼러 이름<input value={c.name} placeholder="이름" maxLength={80} onChange={e=>update({...c,name:e.target.value})}/></label></div>
<div className="lab-fields"><label className="lab-field">사용 손<select value={c.hand} onChange={e=>update({...c,hand:e.target.value as Chart['hand']})}><option value="left">왼손</option><option value="right">오른손</option></select></label><label className="lab-field">그립<select value={c.grip} onChange={e=>update({...c,grip:e.target.value as Chart['grip']})}><option value="thumbless">덤리스</option><option value="twohand">투핸드</option>{!['thumbless','twohand'].includes(c.grip)&&<option value={c.grip}>기존 차트 그립</option>}</select></label></div>
<div className="lab-fields lab-three">{(['middle','ring','bridge'] as const).map(k=><MeasureInput key={k} label={k==='bridge'?'브리지 (inch)':`${k==='middle'?'중지':'약지'} 드릴경 (inch)`} value={k==='bridge'?c.bridge:c[k].diameter} onChange={v=>update(k==='bridge'?{...c,bridge:v}:{...c,[k]:{...c[k],diameter:v}})}/>)}</div>
<details className="lab-detail"><summary>코어 방향 <ChevronDown size={16}/></summary><p>그립을 고정하고 코어를 회전합니다. PIN 배치의 시각적 비교용이며 PAP 레이아웃을 자동 변환하지 않습니다.</p><div className="lab-fields"><Slider label="코어 기울기" value={s.coreTilt} min={-180} max={180} unit="°" onChange={v=>setting('coreTilt',v)}/><Slider label="그립에 대한 회전" value={s.coreTurn} min={-180} max={180} unit="°" onChange={v=>setting('coreTurn',v)}/></div></details>
<details className="lab-detail"><summary>홀 깊이·피치 <ChevronDown size={16}/></summary><p>깊이는 표면 중심부터 드릴 축을 따라 측정합니다. 피치는 차트의 inch 게이지 값과 별개인 시뮬레이션 각도입니다. +전후는 화면 위쪽, +좌우는 화면 오른쪽으로 기울입니다.</p><div className="lab-fields"><Slider label="중지 깊이" value={s.middleDepth} min={10} max={90} unit=" mm" onChange={v=>setting('middleDepth',v)}/><Slider label="약지 깊이" value={s.ringDepth} min={10} max={90} unit=" mm" onChange={v=>setting('ringDepth',v)}/></div><label className="lab-field">피치 모델<select value={s.pitchMode} onChange={e=>setting('pitchMode',e.target.value as Simulation['pitchMode'])}><option value="neutral">중립 0° · 예시</option><option value="degrees">각도 직접 입력</option></select></label>{s.pitchMode==='degrees'&&<div className="lab-fields">{(['middleForward','ringForward','middleSide','ringSide'] as const).map(k=><Slider key={k} label={{middleForward:'중지 전후',ringForward:'약지 전후',middleSide:'중지 좌우',ringSide:'약지 좌우'}[k]} value={s[k]} min={-20} max={20} unit="°" onChange={v=>setting(k,v)}/>)}</div>}</details>
<details className="lab-detail"><summary>지공차트에서 편집 <ChevronDown size={16}/></summary><WorkSheet c={{...c,ball:product?.name??c.ball}} dirty={dirty} onChange={update}/></details>
<div className="lab-save"><label><input type="checkbox" checked={c.shared??false} onChange={e=>update({...c,shared:e.target.checked})}/>차트 공개</label><button onClick={save} disabled={!canSave||busy||loading}><Save size={17}/>{busy?'저장 중…':'차트와 함께 저장'}</button></div>{!canSave&&<p className="lab-help">누구나 가상 지공을 체험할 수 있습니다. 저장은 기존 페이지에서 편집자·관리자로 로그인한 뒤 가능합니다.</p>}{message&&<p className="lab-message" role="status">{message}</p>}
</section></section></div></main>;
}
function Slider({label,value,min,max,unit,onChange}:{label:string;value:number;min:number;max:number;unit:string;onChange:(v:number)=>void}){return <label className="lab-field lab-slider"><span>{label}<output>{value}{unit}</output></span><input aria-label={label} type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;}
function MeasureInput({label,value,onChange}:{label:string;value:Chart['bridge'];onChange:(v:Chart['bridge'])=>void}){const [text,setText]=useState(String(value??'')),[error,setError]=useState('');useEffect(()=>setText(String(value??'')),[value]);return <label className="lab-field">{label}<input value={text} aria-invalid={!!error} onChange={e=>{setText(e.target.value);try{const n=parseMeasureInput(e.target.value);if(typeof n==='number'&&(n<=0||n>2))throw Error('0 초과 2 inch 이하');setError('');onChange(n);}catch{setError('숫자·분수 또는 한글 메모를 입력하세요.');}}}/>{error&&<small role="alert">{error}</small>}</label>;}
