import {hasThumb,gripItems,gripLabel,measureLabel,fingerGripItems,fingerGripLabel} from '@/lib/drill-chart';
import {useState,type ReactNode} from 'react';
import {Choice,Inch,Text,Pitch,Insert} from './chart-fields';
import { Chart, formatInches as f, pitchLabel, missingSpecs } from '@/lib/drill-chart';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
export function GripDrawing({c}:{c:Chart}){
 const left=c.hand==='right'?'middle':'ring',right=c.hand==='right'?'ring':'middle';
 const names={middle:'중지',ring:'약지',thumb:'엄지'};const cx={middle:c.hand==='right'?150:350,ring:c.hand==='right'?350:150,thumb:250};
 return <svg viewBox="0 0 500 355" className="work-drawing" role="img" aria-label="홀 배치 및 스팬과 브리지 수치 작업 도식, 축척 없음">
 <defs><marker id="dimArrow" markerWidth="6" markerHeight="6" refX="3" refY="3" orient="auto-start-reverse"><path d="M6 0L0 3L6 6" fill="none" stroke="currentColor"/></marker></defs>
 <path d="M250 25V325M60 162H440" fill="none" stroke="#9caca4" strokeDasharray="6 4"/>
 <circle cx="250" cy="170" r="150" fill="none" stroke="#a6b8ae"/>
 {[left,right,...(!hasThumb(c.grip)?[]:['thumb'])].map(key=>{const k=key as 'middle'|'ring'|'thumb', x=cx[k], y=k==='thumb'?270:90;return <g key={k}><ellipse cx={x} cy={y} rx={k==='thumb'&&c.spec.ovalShape==='oval'?32:25} ry="25" transform={k==='thumb'&&c.spec.ovalShape==='oval'?`rotate(${(typeof c.spec.ovalAngle==='number'?c.spec.ovalAngle:0)-90} ${x} ${y})`:undefined} fill="#fff" stroke="#375d49" strokeWidth="2"/><path d={`M${x-35} ${y}h70M${x} ${y-35}v70`} stroke="#bac8bf"/><text x={x} y={y-39} textAnchor="middle" fontSize="14" fill="#284c3a">{names[k]}</text><text x={x} y={y+48} textAnchor="middle" fontSize="13">드릴 Ø {measureLabel(c[k].diameter)}</text></g>})}
 <path d="M178 65H222M278 65H322" stroke="#779384"/>
 <text x="250" y="46" textAnchor="middle" fontSize="13">브리지 {measureLabel(c.bridge)}</text>
 {hasThumb(c.grip)&&<><path d="M140 121L219 256M360 121L281 256" fill="none" stroke="#537860" strokeDasharray="3 3"/>
 <rect x="71" y="179" width="126" height="39" fill="#fff"/><text x="134" y="192" textAnchor="middle" fontSize="12">{names[left]} 스팬</text><text x="134" y="210" textAnchor="middle" fontSize="15">{measureLabel(c[left==='middle'?'middleSpan':'ringSpan'])}</text>
 <rect x="303" y="179" width="126" height="39" fill="#fff"/><text x="366" y="192" textAnchor="middle" fontSize="12">{names[right]} 스팬</text><text x="366" y="210" textAnchor="middle" fontSize="15">{measureLabel(c[right==='middle'?'middleSpan':'ringSpan'])}</text></>}
 <text x="12" y="344" fontSize="11" fill="#728378">볼 표면을 바라본 방향 · {c.hand==='right'?'오른손':'왼손'} · 축척 없음</text>
 </svg>
}
function Fold({title,children,enabled,initialOpen=false}:{title:string;children:ReactNode;enabled:boolean;initialOpen?:boolean}){const [open,setOpen]=useState(initialOpen);return enabled?<details className="sheet-fold" open={open} onToggle={e=>setOpen(e.currentTarget.open)} onInvalidCapture={e=>{e.currentTarget.open=true;setOpen(true);}}><summary>{title}</summary><div className="sheet-fold-body">{children}</div></details>:<>{children}</>;}
export function WorkSheet({c,dirty,onChange,compact=true}:{c:Chart;dirty:boolean;compact?:boolean;onChange?:(next:Chart)=>void}){
 const change=<K extends keyof Chart>(key:K,v:Chart[K])=>onChange?.({...c,[key]:v});
 const spec=<K extends keyof Chart['spec']>(key:K,v:Chart['spec'][K])=>change('spec',{...c.spec,[key]:v});
 const text=(label:string,value:string,update:(s:string)=>void,max=120)=><Text label={label} value={value} onChange={update} max={max}/>;

 const missing=missingSpecs(c);const keys:('middle'|'ring'|'thumb')[]=!hasThumb(c.grip)?['middle','ring']:['middle','ring','thumb'];
 const txt=(s:string)=>s||'미입력';const n=measureLabel;
 return <article className={'work-sheet '+(onChange?'editable-sheet ':'')+(compact?'compact-sheet':'')}><header className="sheet-heading"><div><p>FIT STUDIO · PRO SHOP WORK SHEET</p><h2>볼링 지공 작업표</h2></div><div>{onChange?<input aria-label="작업 날짜" type="date" required value={c.spec.date} onChange={e=>spec('date',e.target.value)}/>:c.spec.date}<br/>{missing.length?'작성 중 · 미입력 '+missing.length+'개':'입력 완료 · 작업자 실측 대조용'}{dirty&&<><br/>저장 전 변경 포함</>}</div></header>
 <Fold enabled={compact} title={`${c.name||'새 볼러'} · ${c.ball||'볼 정보'} · 상세 정보`} initialOpen={!c.name}>{onChange?<><p className="sheet-edit-help">표 안의 값을 바로 수정하세요. 변경 후 아래 ‘작업표 저장’을 눌러주세요.</p><div className="sheet-info sheet-edit-info"><div><label>볼러 *<input required maxLength={80} value={c.name} onChange={e=>change('name',e.target.value)}/></label></div><div>{text('볼',c.ball,v=>change('ball',v),100)}</div><div>{text('작업자',c.spec.driller,v=>spec('driller',v),100)}</div><div><Choice label="사용 손" value={c.hand} onChange={v=>change('hand',v as Chart['hand'])} items={[["right","오른손"],["left","왼손"]]}/><Choice label="투구 방식" value={c.grip} onChange={v=>change('grip',v as Chart['grip'])} items={gripItems}/><Choice label="그립 방식" value={c.spec.fingerGrip} onChange={v=>spec('fingerGrip',v as Chart['spec']['fingerGrip'])} items={fingerGripItems}/></div><div><Inch label="무게" value={c.spec.weight} onChange={v=>spec('weight',v)} min={1} max={20} unit="lb" fractions={false}/>{text('시리얼',c.spec.serial,v=>spec('serial',v),100)}</div><div><Inch label="PAP 수평 (+우 / −좌)" value={c.spec.papHorizontal} onChange={v=>spec('papHorizontal',v)} min={-10} max={10}/><Inch label="PAP 수직 (+위 / −아래)" value={c.spec.papVertical} onChange={v=>spec('papVertical',v)} min={-10} max={10}/></div></div></>:<> <div className="sheet-info"><div><span>볼러</span><strong>{txt(c.name)}</strong></div><div><span>볼</span><strong>{txt(c.ball)}</strong></div><div><span>작업자</span><strong>{txt(c.spec.driller)}</strong></div><div><span>손 / 투구 / 그립</span><strong>{c.hand==='right'?'오른손':'왼손'} / {gripLabel(c.grip)} / {fingerGripLabel(c.spec.fingerGrip)}</strong></div><div><span>무게 / 시리얼</span><strong>{n(c.spec.weight,' lb')} / {txt(c.spec.serial)}</strong></div><div><span>PAP</span><strong>수평(+우/−좌) {n(c.spec.papHorizontal)} / 수직(+위/−아래) {n(c.spec.papVertical)}</strong></div></div>
</>}</Fold>
 <div className="sheet-center"><div><Fold enabled={compact} title="홀 배치 그림 보기"><GripDrawing c={c}/></Fold>{onChange&&<div className="sheet-span-edit">{hasThumb(c.grip)&&<><Inch label="중지 스팬" value={c.middleSpan} min={.01} onChange={v=>change('middleSpan',v)}/><Inch label="약지 스팬" value={c.ringSpan} min={.01} onChange={v=>change('ringSpan',v)}/></>}<Inch label="브리지" value={c.bridge} min={.01} max={2} onChange={v=>change('bridge',v)}/></div>}{!onChange&&compact&&<div className="span-summary">{hasThumb(c.grip)&&<><span>중지 스팬 <b>{n(c.middleSpan)}</b></span><span>약지 스팬 <b>{n(c.ringSpan)}</b></span></>}<span>브리지 <b>{n(c.bridge)}</b></span></div>}</div><Fold enabled={compact} title="측정·표기 기준"><div className="sheet-conventions"><h3>측정·표기 기준</h3><p><b>단위</b> inch · 분수와 소수 입력값 유지</p>{onChange&&hasThumb(c.grip)&&<Choice label="스팬 측정 기준" value={c.spec.spanBasis} onChange={v=>spec('spanBasis',v as Chart['spec']['spanBasis'])} items={[["cut","Cut-to-cut"],["finished","Finished"],["unknown","미지정"]]}/>}<p><b>스팬</b> {!hasThumb(c.grip)?'엄지 없음 · 적용 안 함':c.spec.spanBasis==='cut'?'Cut-to-cut · 드릴 절삭 홀의 가까운 가장자리 간 표면 측정값 (베벨 전)':c.spec.spanBasis==='finished'?'Finished · 인서트/엄지 마감 후 접촉 가장자리 간 측정값':'미지정 · 기존 차트의 기준 확인 필요'}</p><p><b>브리지</b> 중지·약지 절삭 홀 사이 가장자리 간격 (베벨 전)</p><p><b>피치 기준</b> {onChange?text('피치 기준',c.spec.pitchReference,v=>spec('pitchReference',v),200):txt(c.spec.pitchReference)}</p><p>F = 그립 중앙 쪽 포워드 / R = 그립 중앙에서 멀어지는 리버스. 좌우는 볼 표면을 바라본 방향이며 손 선택으로 값이 반전되지 않습니다.</p></div></Fold></div>
 <Table className="spec-table"><TableHeader><TableRow><TableHead>항목</TableHead>{keys.map(k=><TableHead key={k}>{({middle:'중지',ring:'약지',thumb:'엄지'})[k]}</TableHead>)}</TableRow></TableHeader><TableBody>
 {([['드릴 외경',k=>n(c[k].diameter)],['전후 피치',k=>pitchLabel(c[k].forward,'forward')],['좌우 피치',k=>pitchLabel(c[k].lateral,'lateral')],['인서트 종류',k=>txt(c[k].insertStyle)],['인서트 사이즈',k=>txt(c[k].insertSize)]] as [string,(k:'middle'|'ring'|'thumb')=>string][]).map(([label,value])=><TableRow key={label}><TableCell>{label}</TableCell>{keys.map(k=><TableCell key={k}>{onChange?<div className="sheet-cell-editor" aria-label={k+' '+label}>{label==='드릴 외경'?<Inch label={({middle:'중지',ring:'약지',thumb:'엄지'})[k]+' '+label} value={c[k]['diameter']} min={.01} max={2} onChange={v=>change(k,{...c[k],['diameter']:v})}/>:label==='전후 피치'||label==='좌우 피치'?<Pitch axis={label==='전후 피치'?'forward':'lateral'} value={c[k][label==='전후 피치'?'forward':'lateral']} onChange={v=>change(k,{...c[k],[label==='전후 피치'?'forward':'lateral']:v})}/>:label==='인서트 종류'?<Insert label={({middle:'중지',ring:'약지',thumb:'엄지'})[k]+' 인서트 종류'} value={c[k].insertStyle} onChange={v=>change(k,{...c[k],insertStyle:v})}/>:<input aria-label={({middle:'중지',ring:'약지',thumb:'엄지'})[k]+' '+label} maxLength={120} placeholder="미입력" value={c[k]['insertSize']} onChange={e=>change(k,{...c[k],['insertSize']:e.target.value})}/>}</div>:value(k)}</TableCell>)}</TableRow>)}
 </TableBody></Table>
 <Fold enabled={compact} title={'엄지 형상 · 레이아웃 · 메모'+(c.notes?' (메모 있음)':'')}><div className="sheet-detail">{onChange&&hasThumb(c.grip)&&<div className="sheet-oval-edit"><Choice label="엄지 형상" value={c.spec.ovalShape} onChange={v=>spec('ovalShape',v as Chart['spec']['ovalShape'])} items={[["round","원형"],["oval","타원"],["unknown","미지정"]]}/>{c.spec.ovalShape==='oval'&&<><Inch label="타원 장축" value={c.spec.ovalLong} min={.01} max={2} onChange={v=>spec('ovalLong',v)}/><Inch label="타원 단축" value={c.spec.ovalShort} min={.01} max={2} onChange={v=>spec('ovalShort',v)}/><Inch label="타원 각도" value={c.spec.ovalAngle} min={0} max={180} unit="°" onChange={v=>spec('ovalAngle',v)}/>{text('타원 각도 기준',c.spec.ovalReference,v=>spec('ovalReference',v),200)}</>}</div>}<p><b>엄지 형상</b> {!hasThumb(c.grip)?'해당 없음':c.spec.ovalShape==='round'?'원형':c.spec.ovalShape==='unknown'?'미지정':`타원 · 마감 장축 ${n(c.spec.ovalLong)} / 단축 ${n(c.spec.ovalShort)} / 각도 ${measureLabel(c.spec.ovalAngle,'°')} · ${txt(c.spec.ovalReference)}`}</p><p><b>레이아웃</b> {onChange?text('레이아웃',c.spec.layout,v=>spec('layout',v),300):txt(c.spec.layout)}</p><p><b>표면 마감</b> {onChange?text('표면 마감',c.spec.finish,v=>spec('finish',v),200):txt(c.spec.finish)}</p><p className="sheet-memo"><b>작업 메모</b> {onChange?<textarea aria-label="작업 메모" rows={3} maxLength={3000} value={c.notes} onChange={e=>change('notes',e.target.value)}/>:txt(c.notes)}</p></div></Fold>
 <Fold enabled={compact} title={missing.length?`미입력 ${missing.length}개 · 작업 안내`:'작업 안내'}>{missing.length>0&&<p className="sheet-missing">미입력: {missing.join(', ')}</p>}
 <footer className="sheet-footer">작업표의 숫자를 게이지·지공 장비에 옮겨 사용하세요. 그림은 1:1 가공 템플릿이 아니며 기계 좌표·타원 가공 이동량을 산출하지 않습니다.<br/>실측 대조 / 작업자 서명: ____________________　날짜: ____________________</footer></Fold></article>
}
