import * as T from 'three';
import {Brush,Evaluator,SUBTRACTION,INTERSECTION} from 'three-bvh-csg';
import {fingerAngles,type Simulation} from './simulation.ts';
export const BALL_RADIUS=108.5;
export const c3Profile=[[0,-.72],[.19,-.71],[.29,-.68],[.36,-.64],[.377,-.61],[.377,-.51],[.40,-.50],[.408,-.46],[.40,-.435],[.403,-.41],[.385,-.37],[.35,-.33],[.405,-.25],[.447,-.18],[.488,-.10],[.519,0],[.537,.10],[.539,.19],[.525,.29],[.50,.39],[.46,.49],[.407,.575],[.343,.645],[.27,.688],[.18,.707],[.08,.712],[0,.712]];
export function coreGeometry(s:Simulation){const g=new T.LatheGeometry(c3Profile.map(([r,y])=>new T.Vector2(r*(.63/.539)*BALL_RADIUS,(y*(1.6/1.432)+.05)*BALL_RADIUS)),64);g.rotateX(T.MathUtils.degToRad(s.coreTilt));g.rotateZ(T.MathUtils.degToRad(s.coreTurn));return g;}
export function holeTools(s:Simulation,d1:number,d2:number,bridge:number,left=true){const angles=fingerAngles(d1,d2,bridge);return angles.map((a,i)=>{a*=left?1:-1;const n=new T.Vector3(Math.sin(a),0,Math.cos(a));const across=new T.Vector3(Math.cos(a),0,-Math.sin(a));const forward=s.pitchMode==='degrees'?(i?s.ringForward:s.middleForward):0,side=s.pitchMode==='degrees'?(i?s.ringSide:s.middleSide):0;
const direction=n.clone().negate().addScaledVector(new T.Vector3(0,1,0),Math.tan(T.MathUtils.degToRad(forward))).addScaledVector(across,Math.tan(T.MathUtils.degToRad(side))).normalize();
const depth=i?s.ringDepth:s.middleDepth;const surface=n.clone().multiplyScalar(BALL_RADIUS);const start=surface.clone().addScaledVector(direction,-4);const center=start.clone().addScaledVector(direction,(depth+4)/2);const g=new T.CylinderGeometry((i?d2:d1)/2,(i?d2:d1)/2,depth+4,32);g.applyQuaternion(new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),direction));g.translate(center.x,center.y,center.z);return {geometry:g,surface,bottom:surface.clone().addScaledVector(direction,depth)};});}
export function subtractHoles(geometry:T.BufferGeometry,tools:{geometry:T.BufferGeometry}[],material:T.Material,cutMaterial:T.Material){const evaluator=new Evaluator();evaluator.useGroups=false;let result=new Brush(geometry,material);result.updateMatrixWorld();const removed:T.BufferGeometry[]=[];for(const tool of tools){const cutter=new Brush(tool.geometry,cutMaterial);cutter.updateMatrixWorld();const cut=evaluator.evaluate(result,cutter,INTERSECTION);removed.push(cut.geometry);const next=evaluator.evaluate(result,cutter,SUBTRACTION);if(result.geometry!==geometry)result.geometry.dispose();result=next;result.updateMatrixWorld();}result.material=material;return {result,removed};}
